services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    container_name: it-caribe-pgsql
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - it-caribe-network

volumes:
  postgresql_data:
    driver: local

networks:
  it-caribe-network:
    external: true
